version: "3.3"

services:
  db:
    image: postgres
    env_file:
      - django.env
    volumes:
      - ./db:/var/lib/postgres
  app:
    build: app
    container_name: django-gunicorn
    restart: always
    env_file:
      - django.env
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    command:
      "gunicorn --workers=2 --bind=0.0.0.0:8000 core.wsgi:application"
    depends_on:
      - db
  nginx:
    image: nginx:1.13
    restart: always
    ports:
      - "8000:80"
    depends_on:
      - app
    networks:
      - nginx_network

volumes:
  db:
  app:

networks:
  nginx_network:
    driver: bridge
