# Generated by Django 4.1.2 on 2023-01-06 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('searching_for_driver', 'در جستجو راننده'), ('waiting_for_driver', 'در انتظار راننده'), ('driver_arrived', 'راننده به مبدا رسیده'), ('passenger_boarded', 'مسافر سوار شده'), ('on_the_way_to_destination', 'در مسیر به مقصد'), ('arrived_at_destination', 'به مقصد رسیده'), ('cancelled', 'سفر لغو شده')], default='searching_for_driver', max_length=256)),
                ('origin_location', models.CharField(max_length=256)),
                ('destination_location', models.CharField(max_length=256)),
                ('total_price', models.IntegerField(default=0)),
                ('payment_method', models.CharField(choices=[('in_cash', 'نقدی'), ('online', 'آنلاین')], default='in_cash', max_length=256)),
                ('paid', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Service.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
